<?php if ($this->isLayerNavigationActive()):?>
<div class="block block-layered-nav" id="solr_search_facets">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
    	<form name="searchFacets" method="get" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>">
			<input type="hidden" name="q" value="<?php echo $this->getData('querytext') ?>" />
    		<?php if($this->isSelectedFacetActive()) : ?>
			<div class="currently">
				<p class="block-subtitle"><?php echo $this->__('Currently Shopping by') ?></p>
				<ol>
					
    				<?php foreach($filterQuery = $this->getFilterQuery() as $key=>$values): ?>
						<?php foreach($values as $v): ?>
							<li>
								<span class="label"><?php echo $this->getFacetLabel($key); ?>:</span> <span class="value"><?php echo $v ?></span>
								<?php $face_key = substr($key, 0, strrpos($key, '_'))?>
								
								<a title="<?php echo $this->__('Remove This Item') ?>" href="<?php echo $this->getRemoveFacesUrl($face_key, $v)?>" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
								
								<?php if ($face_key != 'price'):?>
								<input type="hidden" name="fq[<?php echo $face_key ?>]" value="<?php echo $v?>" />
								<?php endif;?>
							</li>
						<?php endforeach; ?>
					<?php endforeach; ?>
				</ol>
			</div>
			<?php endif; ?>
            <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
            <dl id="narrow-by-list">
				<?php foreach ($this->getFacetFields() as $key=>$face): ?>
                    <?php if (count($face) > 0):?>
	                    <dt id="solr_search_<?php echo $key ?>_expander" onclick="Effect.toggle('content_holder_<?php echo $key ?>', 'slide', { duration: 0.3 }); $('solr_search_<?php echo $key ?>_expander').toggleClassName('collapsed'); return false;"><?php echo $this->getFacetLabel($key); ?></dt>
	                    <dd id="content_holder_<?php echo $key ?>">
	                    	<?php if ($key == 'category_path'):?>
	                    		<?php echo $this->parseCategoryPathFacet($face); ?>
	                    	<?php else:?>
	                    	<ol>
	                    		<?php foreach ($face as $item=>$count): ?>
		                    		<?php if ($count > 0):?>
					                   	<li>							
										<?php $face_key = substr($key, 0, strrpos($key, '_'))?>
										<?php 
										$activeClass = '';
										$facetUrl = $this->getFacesUrl(array('fq'=>array($face_key=>$item)));
										if (isset($filterQuery[$key]) && in_array($item, $filterQuery[$key])){
											$activeClass = 'active';
											$facetUrl = $this->getRemoveFacesUrl($face_key, $v);
										}?>
										<a href="<?php echo $facetUrl?>" class="facet-item <?php echo $activeClass;?>"><?php echo $item?></a> (<?php echo $count?>)
										</li>
									<?php endif;?>
			                	<?php endforeach; ?>
	                    	</ol>
	                    	<?php endif; ?>
	                    </dd>
	                    <div style="clear: both;"></div>
                    <?php endif;?>
                <?php endforeach; ?>
                <?php echo $this->getPriceFacets() ?>
            </dl>
         </form>         
    </div>
</div>
<?php endif;?>