<?php
	$base_url = trim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB),'/');
	
	$display_thumb = $this->helper('solrsearch')->getSettings('solr_quick_search_display_thumnail');
	
	$allow_filter = $this->helper('solrsearch')->getSettings('solr_quick_search_allow_filter');
	
	$currencyPositionSetting = $this->helper('solrsearch')->getSettings('currency_position');
	$currencyPosition = 'before';
	if ($currencyPositionSetting < 1) {
		$currencyPosition = 'after';
	}
		
?>
<form id="search_mini_form" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search') ?>');
            //searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
        <script type="text/javascript">
        //<![CDATA[           

            var Manager;
			/**
			 * Initiate a main point to contact with Solr
			 */
			Manager = new AjaxSolr.Manager({
		      solrUrl: '<?php echo trim($base_url,'/');?>/index.php/search/ajax/query?r='
		    });
		    
            Manager.addWidget(new AjaxSolr.AutocompleteWidget({
			  id: 'autocomplete',
			  target: '#search_mini_form',
			  searchTextPlaceHolder: '<?php echo $this->__('Search') ?>',
			  currencySign: '&nbsp;<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() ?>&nbsp;',
			  field: 'autosuggest',
			  ajaxBaseUrl: '<?php echo trim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB),'/');?>',
			  viewAllResultText: '<?php echo $this->__('View All Search Results for <b>%</b>') ?>',
			  categoryText: '<?php echo $this->__('Categories')?>',
			  keywordsText: '<?php echo $this->__('Keywords')?>',
			  displaykeywordsuggestion: <?php echo ($this->helper('solrsearch')->getSettings('display_keyword_suggestion'))?'true':'false'; ?>,
			  displayResultOfText: '<?php echo $this->__('Display result of <b>%</b>') ?>',
			  displayResultOfInsteadText: '<?php echo $this->__('Display result of <b>%</b> instead') ?>',
			  currencyPos: '<?php echo $currencyPosition ?>',
			  displayThumb: '<?php echo $display_thumb ;?> ',
			  allowFilter: '<?php echo $allow_filter?>'
			}));			
			Manager.init();
        //]]>
        </script>
    </div>
</form>