<!-- NOCACHE key="onsale" -->
<?php
$collection = $this->getProductsOnSale();
if(count($collection) == 0) return;
$_helper = $this->helper('catalog/output');
$page_count = $this->getPageCount();
$per_page = $this->getPerPage();
$speed = $this->getAnimationSpeed();
?>
<script type="text/javascript">
var onsale_page_count = <?php echo $page_count ?>;
var onsale_per_page = <?php echo $per_page ?>;
var cm_onsale_animation_speed = <?php echo $speed ?>;
</script>
<div class="block onsale">
	<div class="block-title"><span>Products On Sale</span></div>
	<div class="block-content">
		<div class="container">
			<table class="products-grid" id="onsale-product-grid">
				<tr>
					<?php foreach($collection as $_product): ?>
						<td class="item">
							<div class="container">
									<?php
										$sticker = $this->helper('stickers')->getThumbnail($_product);
										$label = $this->helper('stickers')->getLabel($_product);
										$sticker_ok = ($sticker || $label) ? true : false;
										$class = $this->helper('stickers')->getPositionClass();
										if($sticker)
											{
												$style = "background-image:url('$sticker');";
												$size = getimagesize($sticker);
												$width = $size[0];
												$height = $size[1];
												$style.= "width:{$width}px;";
												$style.= "height:{$height}px;";
												
												$style = " style=\"$style\"";
												$class.= " image";
											}
									?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php if($sticker_ok): ?><span class="cm-product-sticker product-sticker sticker<?php echo $class ?>"<?php if($sticker) echo $style ?>><span><?php echo $label ?></span></span><?php endif; ?><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->backgroundColor(86,79,75)->resize(200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
								<div class="description">
									<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
									<div class="end-date">
										<?php if($_product->getSpecialToDate()): ?>
											- Sale Ends <?php echo date('m/d', strtotime($_product->getSpecialToDate())) ?>
										<?php endif; ?>
									</div>
									<div class="sku">Model: <?php echo $_product->getSku()?></div>
                  <div class="price-custom">
                    <div class="list-price"><?php echo $this->__('Regular: ') ?><s><?php echo Mage::helper('core')->currency($_product->getmax_suggested_retail_price(),true,true); ?></s></div>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                  </div>
								</div>
							</div>
						</td>
					<?php endforeach; ?>
				</tr>
			</table>
		</div>
	</div>
	<div class="controls" id="onsale-controls">
		<button id="onsale-left"><span>&lt;</span></button>
		<button id="onsale-right"><span>&gt;</span></button>
		<table class="progress">
			<tr>
				<td class="line-left">&nbsp;</td>
				<?php for($i=0; $i<$page_count; $i++): ?>
					<td class="dots" id="onsale-dot-<?php echo $i ?>"></td>
				<?php endfor; ?>
				<td class="line-right">&nbsp;</td>
			</tr>
		</table>
	</div>
</div>
<!-- ENDNOCACHE -->