<div class="itoris-stickers-box" style="position: fixed; left: 0px; height: auto; width: 100%; top: -394px;">
    <div class="itoris-stickers-content-box" style="position: relative; left: 50%; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border-top-color: rgb(205, 0, 0); border-left-color: rgb(205, 0, 0); border-right-color: rgb(205, 0, 0); border-bottom-color: rgb(205, 0, 0); border-top-width: 2px; border-left-width: 2px; border-right-width: 2px; border-bottom-width: 2px; border-top-style: solid; border-left-style: solid; border-right-style: solid; border-bottom-style: solid; width: 785px; height: 390px; margin-left: -394.5px;">
        <div id="itoris_sticker_content_1" class="itoris_sticker_content " style="position: absolute; left: 0px; margin-left: 0px; display: none; z-index: 10000; top: 0px;">
            <div class="content">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('page_sticker')->toHtml(); ?>
            </div>
        </div>
    </div>
    <div class="itoris-stickers-title-box" style="position: relative; left: 50%; height: 29px; margin-left: -79.5px; top: 0px; width: 159px;">
        <img id="itoris_sticker_1" onload="this.isLoaded = true;" class="itoris_sticker itoris-sticker-orientation-top" src="http://www.maxfurniture.com/isticker/index/stickerImage/sticker_id/1/" title="Today's Deals" style="z-index: 10001; width: 159px; height: 29px; float: left;">
    </div>
</div>
<?php /*
<div style="position: fixed; left: 0px; height: auto; width: 100%; top: -394px;">
    <div id="page_sticker-block" style="position: fixed; left: 0px; height: auto; width: 100%; top: -394px;">
        <div class="page_sticker-content"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('page_sticker')->toHtml(); ?></div>
        <div class="page_sticker-title-box" style="position: relative; left: 50%; top: 0px; margin-left: -79.5px; width: 159px; height: 29px;">
            <img src="<?php echo $this->getSkinUrl('images/page_sticker.png')?>" title="Today's Deals" style="float: left; height: 29px; width: 159px; z-index: 10001;">
        </div>
    </div>
</div>
 */
?>