<?php
/**
 * Template for filter items block
 *
 * @see Celebros_Conversionpro_Block_Catalogsearch_Layer_Filter_Attribute
 */
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
		<?php if ($_item->getCount() > 0): ?>
			<?php if (!$this->isHierarchical() && $this->isMultiselectEnabled()): ?>
				<?php if ($_item->isSelected()): ?>
					<input type="checkbox" checked>
				<?php else:?>
					<input type="checkbox">
				<?php endif; ?>
			<?php endif; ?>
			<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
		<?php else: echo $_item->getLabel() ?>
		<?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
			(<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
