<div class="first-box">
	<h4>Recommended Categories</h4>
	<ul>
		<li><a href="/living-room/accent-tables.html" >Accent Tables</a></li>
		<li><a href="/bathroom.html" >Bathroom</a></li>
		<li><a href="/bedroom.html" >Bedrooms</a></li>
		<li><a href="/living-room/chests-cabinets.html" >Chests/Cabinets</a></li>
		<li><a href="/dining.html" >Dining Room</a></li>
		<li><a href="/living-room/tv-carts-centers/wall-media-centers.html" >Entertainment Centers</a></li>
		<li><a href="#" >Media / Game Room</a></li>
		<li><a href="#" >Home Decor</a></li>
		<li><a href="/office.html" >Office Furniture</a></li>
		<li><a href="/living-room.html" >Living Room &amp; Sofas</a></li>
		<li><a href="/bedroom/mattresses.html" >Mattresses</a></li>
		<li><a href="/bathroom/single-vanities.html" >Bathroom Vanities</a></li>
		<li><a href="/outdoor.html" >Outdoor &amp; Patio</a></li>
		<li><a href="/bedroom/youth.html" >Youth Furniture</a></li>
		<li><a href="/clearance.html" >Clearance Offers</a></li>
		<li><a href="/more-categories/warehouse-odds-and-ends.html" >Warehouse Odds and Ends</a></li>
	</ul>	
</div>
<div class="sec-box">
	<h4>Need Assistance?</h4>
	<ul>
		<li><a href="/customer-service/" >Customer Service</a></li>
		<li><a href="/shippinginformation/" >Shipping &amp; Delivery</a></li>
		<li><a href="/faq/" >FAQ's</a></li>
		<li><a href="/returnsandexchanges/" >Returns &amp; Exchanges</a></li>
		<li><a href="/contacts/" >Contact Us</a></li>
		<li><a href="<?php echo Mage::getModel('core/variable')->loadByCode('linkedin')->getValue('plain'); ?>" target="_blank">Max Furniture LinkedIn</a></li>
	</ul>	
</div>
<div  class="third-box">
	<h4>My Account</h4>
	<ul>
		<li><a href="/checkout/cart/">View Cart</a></li>
		<li><a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl() ?>" >Checkout</a></li>
		<li><a href="/customer/account/">My Account</a></li>
		<li><a href="/coupons/" >Coupons &amp; Special Offers</a></li>
		<li><a href="/catalog/seo_sitemap/category/" >Sitemap</a></li>
		<li><a href="/blog/" >Max Furniture Blog</a></li>
	</ul>	
</div>
