<?php
$_productCollection = $this->getProducts();
if(count($_productCollection) == 0) return;
$_helper = $this->helper('catalog/output');
?>
<div class="block block-cartproducts">
	<div class="block-content">
		<ul class="products">
			<?php $_iterator = 0; ?>
			<?php foreach($_productCollection as $_product): ?>
						<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
								<?php // Product Image ?>
									<div class="product-name">
										<div>
											<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
											<input type="checkbox" type="button" id="cart-product-<?php echo $_product->getId() ?>" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="cm_cart_product_click('<?php echo $this->getAddToCartUrl($_product, array('qty' => 1)) ?>', '<?php echo $_product->getRemoveLink() ?>', '<?php echo $_product->getId() ?>')"<?php if($_product->getInCart()) echo ' checked="checked"' ?>/>
											<span class="name" id="cm-cartproducts-title-<?php echo $_product->getId() ?>"><span><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></span></span>
										</div>
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>
										<?php if($_product->getInCart()) echo $this->getPriceHtml($_product, true) ?>
										<div class="desc std">
												<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="#learn-more" title="<?php echo $_productNameStripped ?>" class="link-learn" onclick="cm_cartproducts_popup('<?php echo $_product->getId() ?>')"><?php echo $this->__('Learn More') ?></a>
										</div>
										<div id="cm-cartproducts-description-<?php echo $_product->getId() ?>" style="display:none;"><?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?></div>
						</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<div id="cm-cartproducts-overlay" style="display:none;">
	<div id="cm-cartproducts-popup">
		<span id="cm-cartproducts-close"><span>X</span></span>
		<h3 id="cm-cartproducts-title"></h3>
		<div id="cm-cartproducts-content"></div>
	</div>
</div>
<script type="text/javascript">
// Event.observe(window, 'load', cm_cartproducts_init);
function cm_cartproducts_popup(id)
{
	var desc = $('cm-cartproducts-description-'+id).innerHTML;
	var title = $('cm-cartproducts-title-'+id).innerHTML;
	$('cm-cartproducts-content').update(desc);
	$('cm-cartproducts-title').update(title);
	var overlay = $('cm-cartproducts-overlay');
	
	overlay.show();
	var dimensions = document.viewport.getDimensions();
	var offset = document.viewport.getScrollOffsets();
	var dimensions_new = {
		height: (dimensions.height + offset.top) + 'px',
		width: (dimensions.width) + 'px'
		}
	overlay.setStyle(dimensions_new);
/* IE Hack */
	var IE6 = Prototype.Browser.IE && parseInt(navigator.userAgent.substring(navigator.userAgent.indexOf('MSIE')+5)) == 6;
	if(IE6) {
		$$('select').invoke('hide');
	}
	
	var popup = $('cm-cartproducts-popup');
	var popup_width = popup.getWidth();
	var popup_height = popup.getHeight();
	var offset = document.viewport.getScrollOffsets();
	var width = dimensions.width;
	var left = (width / 2) - (popup_width / 2);
	var height = dimensions.height;
	var top = (height / 2) - (popup_height / 2) /*+ offset.top*/;
	popup.setStyle({
	top: top + 'px',
	left: left + 'px'
	}); 
	
	overlay.observe('click', function(e)  {
		Event.stop(e);
		$('cm-cartproducts-overlay').hide();
	});
	$('cm-cartproducts-close').observe('click', function(e)  {
		Event.stop(e);
		$('cm-cartproducts-overlay').hide();
	});
}
function cm_cart_product_click(add, remove, id)
{
	var check = $('cart-product-'+id);
	if(check.checked)
		{
			setLocation(add);
		}
	else
		{
			setLocation(remove);
		}
}
</script>