<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    $has_description = false;
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        $_description = $this->getCurrentCategory()->getDescription();
        $has_description = true;
    }
?>


<?php
#WDB Show Categories
// $_category = $_category->load($_category->getId());
// highlight_string(print_r($_category, true));
if($_category->getShowCategories() && !(isset($_GET) && !empty($_GET))  && ($children = $_category->getChildrenCategories())) : ?>

  <div class="category-view only-subcats">

    <div class="home-cats list-cats">

    <?php if($_imgHtml): ?>
      <div class="category-description std">
        <?php if($_imgUrl) echo $_imgHtml ?>
        <div class="desc"><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></div>
      </div>
    <?php endif; ?>
    <?php 
      $img_w = 235;
      $img_h = 235;  
      $url1 = $_category->getUrlPath().'?viewall=1';
      $image1 = $_category->getThumbnail();
      $image1 = $image1 ? Mage::getBaseUrl('media').'catalog/category/'.$image1 : "";
    ?>
    <div class="one-cat">
      <div class="title"><a href="/<?php echo $url1 ?>"><span><?php echo $this->__('View All') ?></span></a></div>
      <div class="image">
      <?php if($image1): ?>
        <a href="/<?php echo $url1 ?>"><img src="<?php echo $image1 ?>" alt="<?php echo $_category->getData('name') ?>" width="<?php echo $img_w ?>" height="<?php echo $img_h ?>"/></a>
      <?php endif; ?>
      </div>
    </div>   
    <?php


    $url = '';
    $img_w = 235;
    $img_h = 235;
    $j = 0;
    $next_last = $has_description ? 2 : 4;

    foreach ($children as $child) :
      $j++;
      $last = '';
      $child->load($child->getId());
      
      $url = $child->getUrlPath();
      $image = $child->getThumbnail();
      $image = $image ? Mage::getBaseUrl('media').'catalog/category/'.$image : "";
      
      $image_style = "";
      
      if($image)
        {
          $file = Mage::getBaseDir('media').'/catalog/category/'.$child->getThumbnail();
          if(file_exists($file))
            {
              $size = getimagesize($file);
              $img_w = $size[0];
              $img_h = $size[1];
              
              if($img_h < 235)
                {
                  $padding = (235 - $img_h) / 2;
                  $image_style = "padding-top:{$padding}px";
                }
            }
        }
      if($j == $next_last)
        {
          $last = 'last';
          $j = 0;
          $next_last = 4;
        }
    ?>
    
      <div class="one-cat <?php echo $last ?>">
        <div class="title"><a href="/<?php echo $url ?>"><span><?php echo $child->getData('name') ?></span></a></div>
        <div class="image">
        <?php if($image): ?>
          <a href="/<?php echo $url ?>"><img src="<?php echo $image ?>" alt="<?php echo $child->getData('name') ?>" width="<?php echo $img_w ?>" height="<?php echo $img_h ?>" style="<?php echo $image_style ?>"/></a>
        <?php endif; ?>
        </div>
      </div>

    <?php endforeach ?>

      <div class="clear"></div>
    </div>
  </div>

  <?php return; ?>
<?php endif; ?>


    <?php echo $this->getMessagesBlock()->toHtml() ?>

        <div class="category-view">
            <?php if($this->isContentMode()): ?>
                <?php echo $this->getCmsBlockHtml() ?>

            <?php elseif($this->isMixedMode()): ?>
                <?php echo $this->getCmsBlockHtml() ?>
                <?php echo $this->getProductListHtml() ?>

            <?php else: ?>
                <?php echo $this->getProductListHtml() ?>
            <?php endif; ?>
        </div>
